name = "LatticeGeometry"
uuid = "a9deb695-1ab1-4287-81b1-7b7be27b3be4"
authors = ["nattyo1226 <132973057+nattyo1226@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Printf = "1.11.0"
julia = "1.11.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
